import simd

// Generated by tools/lod_colors.py from Minecraft 26.3's block textures: the mean color of each material's
// representative texture's opaque texels, with the plains grass/foliage/water tints. Indexed by
// MetalMCCore.Mat raw value. Keeps far LOD terrain close to the average color of vanilla's textured
// terrain at the seam.
let lodMaterialColors: [SIMD4<Float>] = [
    SIMD4(0, 0, 0, 0),   // air
    SIMD4(0.492, 0.492, 0.492, 1),   // stone
    SIMD4(0.526, 0.378, 0.263, 1),   // dirt
    SIMD4(0.329, 0.429, 0.202, 1),   // grass
    SIMD4(0.859, 0.813, 0.640, 1),   // sand
    SIMD4(0.172, 0.321, 0.621, 1),   // water
    SIMD4(0.780, 0.350, 0.780, 1),   // unknown
    SIMD4(0.314, 0.314, 0.324, 1),   // deepslate
    SIMD4(0.517, 0.500, 0.496, 1),   // gravel
    SIMD4(0.428, 0.334, 0.199, 1),   // log
    SIMD4(0.636, 0.513, 0.308, 1),   // planks
    SIMD4(0.264, 0.379, 0.104, 1),   // leaves
    SIMD4(0.900, 0.678, 0.761, 1),   // cherryLeaves
    SIMD4(0.977, 0.997, 0.997, 1),   // snow
    SIMD4(0.571, 0.721, 0.996, 1),   // ice
    SIMD4(0.630, 0.653, 0.704, 1),   // clay
    SIMD4(0.597, 0.369, 0.266, 1),   // terracotta
    SIMD4(0.833, 0.353, 0.071, 1),   // lava
    SIMD4(0.501, 0.499, 0.500, 1),   // cobblestone
    SIMD4(0.592, 0.383, 0.326, 1),   // bricks
    SIMD4(0.582, 0.477, 0.256, 1),   // path
    SIMD4(0.561, 0.402, 0.278, 1),   // farmland
    SIMD4(0.651, 0.546, 0.049, 1),   // hay
    SIMD4(0.916, 0.927, 0.929, 1),   // wool
    SIMD4(0.349, 0.430, 0.178, 1),   // moss
    SIMD4(0.215, 0.129, 0.174, 1),   // cherryWood
    SIMD4(0.717, 0.718, 0.714, 1),   // lightStone
    SIMD4(0.586, 0.405, 0.337, 1),   // granite
    SIMD4(0.878, 0.840, 0.668, 1),   // sandstone
    SIMD4(0.236, 0.225, 0.238, 1),   // mud
    SIMD4(0.525, 0.384, 0.750, 1),   // amethyst
    SIMD4(0.767, 0.450, 0.095, 1),   // pumpkin
]
