import simd

// Generated by lod_colors.py from Minecraft 26.3's block textures: the mean color of each material's
// representative textures' opaque texels, with the plains grass/foliage/water tints. Three entries per
// material (top, side, bottom), indexed by MetalMCCore.Mat raw value * 3. Keeps far LOD terrain close to
// the average color of vanilla's textured terrain at the seam.
let lodMaterialFaceColors: [SIMD4<Float>] = [
    SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0),   // air
    SIMD4(0.492, 0.492, 0.492, 1), SIMD4(0.492, 0.492, 0.492, 1), SIMD4(0.492, 0.492, 0.492, 1),   // stone
    SIMD4(0.526, 0.378, 0.263, 1), SIMD4(0.526, 0.378, 0.263, 1), SIMD4(0.526, 0.378, 0.263, 1),   // dirt
    SIMD4(0.329, 0.429, 0.202, 1), SIMD4(0.480, 0.379, 0.246, 1), SIMD4(0.526, 0.378, 0.263, 1),   // grass
    SIMD4(0.859, 0.813, 0.640, 1), SIMD4(0.859, 0.813, 0.640, 1), SIMD4(0.859, 0.813, 0.640, 1),   // sand
    SIMD4(0.172, 0.321, 0.621, 1), SIMD4(0.172, 0.321, 0.621, 1), SIMD4(0.172, 0.321, 0.621, 1),   // water
    SIMD4(0.492, 0.492, 0.492, 1), SIMD4(0.492, 0.492, 0.492, 1), SIMD4(0.492, 0.492, 0.492, 1),   // unknown
    SIMD4(0.342, 0.342, 0.351, 1), SIMD4(0.314, 0.314, 0.324, 1), SIMD4(0.342, 0.342, 0.351, 1),   // deepslate
    SIMD4(0.517, 0.500, 0.496, 1), SIMD4(0.517, 0.500, 0.496, 1), SIMD4(0.517, 0.500, 0.496, 1),   // gravel
    SIMD4(0.594, 0.477, 0.286, 1), SIMD4(0.428, 0.334, 0.199, 1), SIMD4(0.594, 0.477, 0.286, 1),   // log
    SIMD4(0.636, 0.513, 0.308, 1), SIMD4(0.636, 0.513, 0.308, 1), SIMD4(0.636, 0.513, 0.308, 1),   // planks
    SIMD4(0.264, 0.379, 0.104, 1), SIMD4(0.264, 0.379, 0.104, 1), SIMD4(0.264, 0.379, 0.104, 1),   // leaves
    SIMD4(0.900, 0.678, 0.761, 1), SIMD4(0.900, 0.678, 0.761, 1), SIMD4(0.900, 0.678, 0.761, 1),   // cherryLeaves
    SIMD4(0.977, 0.997, 0.997, 1), SIMD4(0.977, 0.997, 0.997, 1), SIMD4(0.977, 0.997, 0.997, 1),   // snow
    SIMD4(0.571, 0.721, 0.996, 1), SIMD4(0.571, 0.721, 0.996, 1), SIMD4(0.571, 0.721, 0.996, 1),   // ice
    SIMD4(0.630, 0.653, 0.704, 1), SIMD4(0.630, 0.653, 0.704, 1), SIMD4(0.630, 0.653, 0.704, 1),   // clay
    SIMD4(0.597, 0.369, 0.266, 1), SIMD4(0.597, 0.369, 0.266, 1), SIMD4(0.597, 0.369, 0.266, 1),   // terracotta
    SIMD4(0.833, 0.353, 0.071, 1), SIMD4(0.833, 0.353, 0.071, 1), SIMD4(0.833, 0.353, 0.071, 1),   // lava
    SIMD4(0.501, 0.499, 0.500, 1), SIMD4(0.501, 0.499, 0.500, 1), SIMD4(0.501, 0.499, 0.500, 1),   // cobblestone
    SIMD4(0.592, 0.383, 0.326, 1), SIMD4(0.592, 0.383, 0.326, 1), SIMD4(0.592, 0.383, 0.326, 1),   // bricks
    SIMD4(0.582, 0.477, 0.256, 1), SIMD4(0.535, 0.396, 0.261, 1), SIMD4(0.526, 0.378, 0.263, 1),   // path
    SIMD4(0.561, 0.402, 0.278, 1), SIMD4(0.526, 0.378, 0.263, 1), SIMD4(0.526, 0.378, 0.263, 1),   // farmland
    SIMD4(0.651, 0.546, 0.049, 1), SIMD4(0.653, 0.536, 0.150, 1), SIMD4(0.651, 0.546, 0.049, 1),   // hay
    SIMD4(0.916, 0.927, 0.929, 1), SIMD4(0.916, 0.927, 0.929, 1), SIMD4(0.916, 0.927, 0.929, 1),   // wool
    SIMD4(0.349, 0.430, 0.178, 1), SIMD4(0.349, 0.430, 0.178, 1), SIMD4(0.349, 0.430, 0.178, 1),   // moss
    SIMD4(0.726, 0.553, 0.538, 1), SIMD4(0.215, 0.129, 0.174, 1), SIMD4(0.726, 0.553, 0.538, 1),   // cherryWood
    SIMD4(0.876, 0.880, 0.865, 1), SIMD4(0.876, 0.880, 0.865, 1), SIMD4(0.876, 0.880, 0.865, 1),   // lightStone
    SIMD4(0.586, 0.405, 0.337, 1), SIMD4(0.586, 0.405, 0.337, 1), SIMD4(0.586, 0.405, 0.337, 1),   // granite
    SIMD4(0.878, 0.840, 0.668, 1), SIMD4(0.849, 0.797, 0.611, 1), SIMD4(0.846, 0.792, 0.605, 1),   // sandstone
    SIMD4(0.236, 0.225, 0.238, 1), SIMD4(0.236, 0.225, 0.238, 1), SIMD4(0.236, 0.225, 0.238, 1),   // mud
    SIMD4(0.525, 0.384, 0.750, 1), SIMD4(0.525, 0.384, 0.750, 1), SIMD4(0.525, 0.384, 0.750, 1),   // amethyst
    SIMD4(0.777, 0.466, 0.096, 1), SIMD4(0.767, 0.450, 0.095, 1), SIMD4(0.777, 0.466, 0.096, 1),   // pumpkin
    SIMD4(0.534, 0.534, 0.536, 1), SIMD4(0.534, 0.534, 0.536, 1), SIMD4(0.534, 0.534, 0.536, 1),   // andesite
    SIMD4(0.740, 0.739, 0.741, 1), SIMD4(0.740, 0.739, 0.741, 1), SIMD4(0.740, 0.739, 0.741, 1),   // diorite
    SIMD4(0.424, 0.428, 0.402, 1), SIMD4(0.424, 0.428, 0.402, 1), SIMD4(0.424, 0.428, 0.402, 1),   // tuff
    SIMD4(0.527, 0.422, 0.363, 1), SIMD4(0.527, 0.422, 0.363, 1), SIMD4(0.527, 0.422, 0.363, 1),   // dripstone
    SIMD4(0.468, 0.336, 0.233, 1), SIMD4(0.468, 0.336, 0.233, 1), SIMD4(0.468, 0.336, 0.233, 1),   // coarseDirt
    SIMD4(0.360, 0.248, 0.094, 1), SIMD4(0.480, 0.344, 0.224, 1), SIMD4(0.526, 0.378, 0.263, 1),   // podzol
    SIMD4(0.436, 0.387, 0.397, 1), SIMD4(0.445, 0.344, 0.282, 1), SIMD4(0.526, 0.378, 0.263, 1),   // mycelium
    SIMD4(0.748, 0.404, 0.130, 1), SIMD4(0.748, 0.404, 0.130, 1), SIMD4(0.748, 0.404, 0.130, 1),   // redSand
    SIMD4(0.711, 0.384, 0.123, 1), SIMD4(0.732, 0.390, 0.114, 1), SIMD4(0.728, 0.386, 0.111, 1),   // redSandstone
    SIMD4(0.822, 0.698, 0.633, 1), SIMD4(0.822, 0.698, 0.633, 1), SIMD4(0.822, 0.698, 0.633, 1),   // whiteTerracotta
    SIMD4(0.634, 0.329, 0.148, 1), SIMD4(0.634, 0.329, 0.148, 1), SIMD4(0.634, 0.329, 0.148, 1),   // orangeTerracotta
    SIMD4(0.730, 0.522, 0.139, 1), SIMD4(0.730, 0.522, 0.139, 1), SIMD4(0.730, 0.522, 0.139, 1),   // yellowTerracotta
    SIMD4(0.561, 0.239, 0.184, 1), SIMD4(0.561, 0.239, 0.184, 1), SIMD4(0.561, 0.239, 0.184, 1),   // redTerracotta
    SIMD4(0.303, 0.201, 0.140, 1), SIMD4(0.303, 0.201, 0.140, 1), SIMD4(0.303, 0.201, 0.140, 1),   // brownTerracotta
    SIMD4(0.530, 0.419, 0.382, 1), SIMD4(0.530, 0.419, 0.382, 1), SIMD4(0.530, 0.419, 0.382, 1),   // lightGrayTerracotta
    SIMD4(0.555, 0.706, 0.982, 1), SIMD4(0.555, 0.706, 0.982, 1), SIMD4(0.555, 0.706, 0.982, 1),   // packedIce
    SIMD4(0.455, 0.657, 0.992, 1), SIMD4(0.455, 0.657, 0.992, 1), SIMD4(0.455, 0.657, 0.992, 1),   // blueIce
    SIMD4(0.059, 0.042, 0.096, 1), SIMD4(0.059, 0.042, 0.096, 1), SIMD4(0.059, 0.042, 0.096, 1),   // obsidian
    SIMD4(0.861, 0.874, 0.621, 1), SIMD4(0.861, 0.874, 0.621, 1), SIMD4(0.861, 0.874, 0.621, 1),   // endStone
    SIMD4(0.666, 0.494, 0.665, 1), SIMD4(0.666, 0.494, 0.665, 1), SIMD4(0.666, 0.494, 0.665, 1),   // purpur
    SIMD4(0.368, 0.224, 0.368, 1), SIMD4(0.368, 0.224, 0.368, 1), SIMD4(0.368, 0.224, 0.368, 1),   // chorus
    SIMD4(0.674, 0.514, 0.331, 1), SIMD4(0.674, 0.514, 0.331, 1), SIMD4(0.674, 0.514, 0.331, 1),   // glowstone
    SIMD4(0.676, 0.784, 0.745, 1), SIMD4(0.676, 0.784, 0.745, 1), SIMD4(0.676, 0.784, 0.745, 1),   // seaLantern
    SIMD4(0.945, 0.575, 0.278, 1), SIMD4(0.945, 0.575, 0.278, 1), SIMD4(0.945, 0.575, 0.278, 1),   // shroomlight
    SIMD4(0.777, 0.466, 0.096, 1), SIMD4(0.841, 0.598, 0.207, 1), SIMD4(0.777, 0.466, 0.096, 1),   // jackOLantern
    SIMD4(0.983, 0.961, 0.810, 1), SIMD4(0.963, 0.915, 0.713, 1), SIMD4(0.983, 0.961, 0.810, 1),   // froglight
    SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0),   // light15
    SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0),   // light14
    SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0),   // light10
    SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0),   // light7
    SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0),   // (id 62)
    SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0),   // (id 63)
    SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0),   // (id 64)
    SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0),   // (id 65)
    SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0),   // (id 66)
    SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0),   // (id 67)
    SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0),   // (id 68)
    SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0),   // (id 69)
    SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0),   // (id 70)
    SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0),   // (id 71)
    SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0),   // (id 72)
    SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0),   // (id 73)
    SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0),   // (id 74)
    SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0),   // (id 75)
    SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0),   // (id 76)
    SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0),   // (id 77)
    SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0),   // (id 78)
    SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0),   // (id 79)
    SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0),   // (id 80)
    SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0),   // (id 81)
    SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0),   // (id 82)
    SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0),   // (id 83)
    SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0),   // (id 84)
    SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0),   // (id 85)
    SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0),   // (id 86)
    SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0),   // (id 87)
    SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0),   // (id 88)
    SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0),   // (id 89)
    SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0),   // (id 90)
    SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0),   // (id 91)
    SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0),   // (id 92)
    SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0),   // (id 93)
    SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0),   // (id 94)
    SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0),   // (id 95)
    SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0),   // (id 96)
    SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0),   // (id 97)
    SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0),   // (id 98)
    SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0),   // (id 99)
    SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0),   // (id 100)
    SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0),   // (id 101)
    SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0),   // (id 102)
    SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0),   // (id 103)
    SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0),   // (id 104)
    SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0),   // (id 105)
    SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0),   // (id 106)
    SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0),   // (id 107)
    SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0),   // (id 108)
    SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0),   // (id 109)
    SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0),   // (id 110)
    SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0),   // (id 111)
    SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0),   // (id 112)
    SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0),   // (id 113)
    SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0),   // (id 114)
    SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0),   // (id 115)
    SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0),   // (id 116)
    SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0),   // (id 117)
    SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0),   // (id 118)
    SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0),   // (id 119)
    SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0),   // (id 120)
    SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0),   // (id 121)
    SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0),   // (id 122)
    SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0),   // (id 123)
    SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0),   // (id 124)
    SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0),   // (id 125)
    SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0),   // (id 126)
    SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0),   // (id 127)
    SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0),   // (id 128)
    SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0),   // (id 129)
    SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0),   // (id 130)
    SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0),   // (id 131)
    SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0),   // (id 132)
    SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0),   // (id 133)
    SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0),   // (id 134)
    SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0),   // (id 135)
    SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0),   // (id 136)
    SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0),   // (id 137)
    SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0),   // (id 138)
    SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0),   // (id 139)
    SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0),   // (id 140)
    SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0),   // (id 141)
    SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0),   // (id 142)
    SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0),   // (id 143)
    SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0),   // (id 144)
    SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0),   // (id 145)
    SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0),   // (id 146)
    SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0),   // (id 147)
    SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0),   // (id 148)
    SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0),   // (id 149)
    SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0),   // (id 150)
    SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0),   // (id 151)
    SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0),   // (id 152)
    SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0),   // (id 153)
    SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0),   // (id 154)
    SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0),   // (id 155)
    SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0),   // (id 156)
    SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0),   // (id 157)
    SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0),   // (id 158)
    SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0), SIMD4(0, 0, 0, 0),   // (id 159)
    SIMD4(0.842, 0.524, 0.158, 1), SIMD4(0.842, 0.524, 0.158, 1), SIMD4(0.842, 0.524, 0.158, 1),   // yellowPoplarLeaves
    SIMD4(0.604, 0.174, 0.154, 1), SIMD4(0.604, 0.174, 0.154, 1), SIMD4(0.604, 0.174, 0.154, 1),   // redPoplarLeaves
    SIMD4(0.739, 0.339, 0.094, 1), SIMD4(0.739, 0.339, 0.094, 1), SIMD4(0.739, 0.339, 0.094, 1),   // orangePoplarLeaves
    SIMD4(0.785, 0.184, 0.177, 1), SIMD4(0.785, 0.184, 0.177, 1), SIMD4(0.785, 0.184, 0.177, 1),   // redMushroomBlock
    SIMD4(0.586, 0.438, 0.319, 1), SIMD4(0.586, 0.438, 0.319, 1), SIMD4(0.586, 0.438, 0.319, 1),   // brownMushroomBlock
    SIMD4(0.797, 0.771, 0.728, 1), SIMD4(0.797, 0.771, 0.728, 1), SIMD4(0.797, 0.771, 0.728, 1),   // mushroomStem
    SIMD4(0.390, 0.613, 0.592, 1), SIMD4(0.390, 0.613, 0.592, 1), SIMD4(0.390, 0.613, 0.592, 1),   // prismarine
    SIMD4(0.203, 0.359, 0.298, 1), SIMD4(0.203, 0.359, 0.298, 1), SIMD4(0.203, 0.359, 0.298, 1),   // darkPrismarine
    SIMD4(0.560, 0.249, 0.124, 1), SIMD4(0.560, 0.249, 0.124, 1), SIMD4(0.560, 0.249, 0.124, 1),   // magma
]

/// Grass block sides: the untinted dirt part's mean color, the tinted fringe's share of the texture, and the
/// fringe overlay's mean gray. Side color for tint T = (1 - fringe) * base + fringe * gray * T.
let lodGrassSideBase = SIMD3<Float>(0.508, 0.364, 0.253)
let lodGrassSideFringe: Float = 0.176
let lodGrassOverlayGray: Float = 0.606

/// Block textures used for LOD texture detail (names under block/ in the block atlas), with the mean luma
/// of each texture's opaque texels. The LOD multiplies its flat color by texel luma / mean luma. The mean
/// colors (vanilla's textures, untinted) let a resource pack's textures scale the LOD's colors (LodTextures).
struct LodSprite {
    let top: String
    let side: String
    let topLuma: Float
    let sideLuma: Float
    let topMean: SIMD3<Float>
    let sideMean: SIMD3<Float>
}

let lodMaterialSprites: [LodSprite] = [
    LodSprite(top: "", side: "", topLuma: 1, sideLuma: 1, topMean: SIMD3(1, 1, 1), sideMean: SIMD3(1, 1, 1)),   // air
    LodSprite(top: "stone", side: "stone", topLuma: 0.492, sideLuma: 0.492, topMean: SIMD3(0.492, 0.492, 0.492), sideMean: SIMD3(0.492, 0.492, 0.492)),   // stone
    LodSprite(top: "dirt", side: "dirt", topLuma: 0.401, sideLuma: 0.401, topMean: SIMD3(0.526, 0.378, 0.263), sideMean: SIMD3(0.526, 0.378, 0.263)),   // dirt
    LodSprite(top: "grass_block_top", side: "dirt", topLuma: 0.578, sideLuma: 0.401, topMean: SIMD3(0.578, 0.578, 0.578), sideMean: SIMD3(0.526, 0.378, 0.263)),   // grass
    LodSprite(top: "sand", side: "sand", topLuma: 0.810, sideLuma: 0.810, topMean: SIMD3(0.859, 0.813, 0.640), sideMean: SIMD3(0.859, 0.813, 0.640)),   // sand
    LodSprite(top: "water_still", side: "water_still", topLuma: 0.694, sideLuma: 0.694, topMean: SIMD3(0.694, 0.694, 0.694), sideMean: SIMD3(0.694, 0.694, 0.694)),   // water
    LodSprite(top: "stone", side: "stone", topLuma: 0.492, sideLuma: 0.492, topMean: SIMD3(0.492, 0.492, 0.492), sideMean: SIMD3(0.492, 0.492, 0.492)),   // unknown
    LodSprite(top: "deepslate_top", side: "deepslate", topLuma: 0.343, sideLuma: 0.315, topMean: SIMD3(0.342, 0.342, 0.351), sideMean: SIMD3(0.314, 0.314, 0.324)),   // deepslate
    LodSprite(top: "gravel", side: "gravel", topLuma: 0.503, sideLuma: 0.503, topMean: SIMD3(0.517, 0.500, 0.496), sideMean: SIMD3(0.517, 0.500, 0.496)),   // gravel
    LodSprite(top: "oak_log_top", side: "oak_log", topLuma: 0.488, sideLuma: 0.344, topMean: SIMD3(0.594, 0.477, 0.286), sideMean: SIMD3(0.428, 0.334, 0.199)),   // log
    LodSprite(top: "oak_planks", side: "oak_planks", topLuma: 0.524, sideLuma: 0.524, topMean: SIMD3(0.636, 0.513, 0.308), sideMean: SIMD3(0.636, 0.513, 0.308)),   // planks
    LodSprite(top: "oak_leaves", side: "oak_leaves", topLuma: 0.565, sideLuma: 0.565, topMean: SIMD3(0.566, 0.565, 0.566), sideMean: SIMD3(0.566, 0.565, 0.566)),   // leaves
    LodSprite(top: "cherry_leaves", side: "cherry_leaves", topLuma: 0.731, sideLuma: 0.731, topMean: SIMD3(0.900, 0.678, 0.761), sideMean: SIMD3(0.900, 0.678, 0.761)),   // cherryLeaves
    LodSprite(top: "snow", side: "snow", topLuma: 0.993, sideLuma: 0.993, topMean: SIMD3(0.977, 0.997, 0.997), sideMean: SIMD3(0.977, 0.997, 0.997)),   // snow
    LodSprite(top: "ice", side: "ice", topLuma: 0.709, sideLuma: 0.709, topMean: SIMD3(0.571, 0.721, 0.996), sideMean: SIMD3(0.571, 0.721, 0.996)),   // ice
    LodSprite(top: "clay", side: "clay", topLuma: 0.652, sideLuma: 0.652, topMean: SIMD3(0.630, 0.653, 0.704), sideMean: SIMD3(0.630, 0.653, 0.704)),   // clay
    LodSprite(top: "terracotta", side: "terracotta", topLuma: 0.410, sideLuma: 0.410, topMean: SIMD3(0.597, 0.369, 0.266), sideMean: SIMD3(0.597, 0.369, 0.266)),   // terracotta
    LodSprite(top: "lava_still", side: "lava_still", topLuma: 0.435, sideLuma: 0.435, topMean: SIMD3(0.833, 0.353, 0.071), sideMean: SIMD3(0.833, 0.353, 0.071)),   // lava
    LodSprite(top: "cobblestone", side: "cobblestone", topLuma: 0.500, sideLuma: 0.500, topMean: SIMD3(0.501, 0.499, 0.500), sideMean: SIMD3(0.501, 0.499, 0.500)),   // cobblestone
    LodSprite(top: "bricks", side: "bricks", topLuma: 0.423, sideLuma: 0.423, topMean: SIMD3(0.592, 0.383, 0.326), sideMean: SIMD3(0.592, 0.383, 0.326)),   // bricks
    LodSprite(top: "dirt_path_top", side: "dirt_path_side", topLuma: 0.483, sideLuma: 0.416, topMean: SIMD3(0.582, 0.477, 0.256), sideMean: SIMD3(0.535, 0.396, 0.261)),   // path
    LodSprite(top: "farmland", side: "dirt", topLuma: 0.427, sideLuma: 0.401, topMean: SIMD3(0.561, 0.402, 0.278), sideMean: SIMD3(0.526, 0.378, 0.263)),   // farmland
    LodSprite(top: "hay_block_top", side: "hay_block_side", topLuma: 0.532, sideLuma: 0.533, topMean: SIMD3(0.651, 0.546, 0.049), sideMean: SIMD3(0.653, 0.536, 0.150)),   // hay
    LodSprite(top: "white_wool", side: "white_wool", topLuma: 0.925, sideLuma: 0.925, topMean: SIMD3(0.916, 0.927, 0.929), sideMean: SIMD3(0.916, 0.927, 0.929)),   // wool
    LodSprite(top: "moss_block", side: "moss_block", topLuma: 0.395, sideLuma: 0.395, topMean: SIMD3(0.349, 0.430, 0.178), sideMean: SIMD3(0.349, 0.430, 0.178)),   // moss
    LodSprite(top: "cherry_log_top", side: "cherry_log", topLuma: 0.589, sideLuma: 0.151, topMean: SIMD3(0.726, 0.553, 0.538), sideMean: SIMD3(0.215, 0.129, 0.174)),   // cherryWood
    LodSprite(top: "calcite", side: "calcite", topLuma: 0.878, sideLuma: 0.878, topMean: SIMD3(0.876, 0.880, 0.865), sideMean: SIMD3(0.876, 0.880, 0.865)),   // lightStone
    LodSprite(top: "granite", side: "granite", topLuma: 0.438, sideLuma: 0.438, topMean: SIMD3(0.586, 0.405, 0.337), sideMean: SIMD3(0.586, 0.405, 0.337)),   // granite
    LodSprite(top: "sandstone_top", side: "sandstone", topLuma: 0.836, sideLuma: 0.795, topMean: SIMD3(0.878, 0.840, 0.668), sideMean: SIMD3(0.849, 0.797, 0.611)),   // sandstone
    LodSprite(top: "mud", side: "mud", topLuma: 0.229, sideLuma: 0.229, topMean: SIMD3(0.236, 0.225, 0.238), sideMean: SIMD3(0.236, 0.225, 0.238)),   // mud
    LodSprite(top: "amethyst_block", side: "amethyst_block", topLuma: 0.441, sideLuma: 0.441, topMean: SIMD3(0.525, 0.384, 0.750), sideMean: SIMD3(0.525, 0.384, 0.750)),   // amethyst
    LodSprite(top: "pumpkin_top", side: "pumpkin_side", topLuma: 0.505, sideLuma: 0.492, topMean: SIMD3(0.777, 0.466, 0.096), sideMean: SIMD3(0.767, 0.450, 0.095)),   // pumpkin
    LodSprite(top: "andesite", side: "andesite", topLuma: 0.534, sideLuma: 0.534, topMean: SIMD3(0.534, 0.534, 0.536), sideMean: SIMD3(0.534, 0.534, 0.536)),   // andesite
    LodSprite(top: "diorite", side: "diorite", topLuma: 0.739, sideLuma: 0.739, topMean: SIMD3(0.740, 0.739, 0.741), sideMean: SIMD3(0.740, 0.739, 0.741)),   // diorite
    LodSprite(top: "tuff", side: "tuff", topLuma: 0.425, sideLuma: 0.425, topMean: SIMD3(0.424, 0.428, 0.402), sideMean: SIMD3(0.424, 0.428, 0.402)),   // tuff
    LodSprite(top: "dripstone_block", side: "dripstone_block", topLuma: 0.440, sideLuma: 0.440, topMean: SIMD3(0.527, 0.422, 0.363), sideMean: SIMD3(0.527, 0.422, 0.363)),   // dripstone
    LodSprite(top: "coarse_dirt", side: "coarse_dirt", topLuma: 0.356, sideLuma: 0.356, topMean: SIMD3(0.468, 0.336, 0.233), sideMean: SIMD3(0.468, 0.336, 0.233)),   // coarseDirt
    LodSprite(top: "podzol_top", side: "podzol_side", topLuma: 0.261, sideLuma: 0.364, topMean: SIMD3(0.360, 0.248, 0.094), sideMean: SIMD3(0.480, 0.344, 0.224)),   // podzol
    LodSprite(top: "mycelium_top", side: "mycelium_side", topLuma: 0.398, sideLuma: 0.361, topMean: SIMD3(0.436, 0.387, 0.397), sideMean: SIMD3(0.445, 0.344, 0.282)),   // mycelium
    LodSprite(top: "red_sand", side: "red_sand", topLuma: 0.457, sideLuma: 0.457, topMean: SIMD3(0.748, 0.404, 0.130), sideMean: SIMD3(0.748, 0.404, 0.130)),   // redSand
    LodSprite(top: "red_sandstone_top", side: "red_sandstone", topLuma: 0.434, sideLuma: 0.443, topMean: SIMD3(0.711, 0.384, 0.123), sideMean: SIMD3(0.732, 0.390, 0.114)),   // redSandstone
    LodSprite(top: "white_terracotta", side: "white_terracotta", topLuma: 0.720, sideLuma: 0.720, topMean: SIMD3(0.822, 0.698, 0.633), sideMean: SIMD3(0.822, 0.698, 0.633)),   // whiteTerracotta
    LodSprite(top: "orange_terracotta", side: "orange_terracotta", topLuma: 0.381, sideLuma: 0.381, topMean: SIMD3(0.634, 0.329, 0.148), sideMean: SIMD3(0.634, 0.329, 0.148)),   // orangeTerracotta
    LodSprite(top: "yellow_terracotta", side: "yellow_terracotta", topLuma: 0.539, sideLuma: 0.539, topMean: SIMD3(0.730, 0.522, 0.139), sideMean: SIMD3(0.730, 0.522, 0.139)),   // yellowTerracotta
    LodSprite(top: "red_terracotta", side: "red_terracotta", topLuma: 0.304, sideLuma: 0.304, topMean: SIMD3(0.561, 0.239, 0.184), sideMean: SIMD3(0.561, 0.239, 0.184)),   // redTerracotta
    LodSprite(top: "brown_terracotta", side: "brown_terracotta", topLuma: 0.218, sideLuma: 0.218, topMean: SIMD3(0.303, 0.201, 0.140), sideMean: SIMD3(0.303, 0.201, 0.140)),   // brownTerracotta
    LodSprite(top: "light_gray_terracotta", side: "light_gray_terracotta", topLuma: 0.440, sideLuma: 0.440, topMean: SIMD3(0.530, 0.419, 0.382), sideMean: SIMD3(0.530, 0.419, 0.382)),   // lightGrayTerracotta
    LodSprite(top: "packed_ice", side: "packed_ice", topLuma: 0.694, sideLuma: 0.694, topMean: SIMD3(0.555, 0.706, 0.982), sideMean: SIMD3(0.555, 0.706, 0.982)),   // packedIce
    LodSprite(top: "blue_ice", side: "blue_ice", topLuma: 0.639, sideLuma: 0.639, topMean: SIMD3(0.455, 0.657, 0.992), sideMean: SIMD3(0.455, 0.657, 0.992)),   // blueIce
    LodSprite(top: "obsidian", side: "obsidian", topLuma: 0.049, sideLuma: 0.049, topMean: SIMD3(0.059, 0.042, 0.096), sideMean: SIMD3(0.059, 0.042, 0.096)),   // obsidian
    LodSprite(top: "end_stone", side: "end_stone", topLuma: 0.853, sideLuma: 0.853, topMean: SIMD3(0.861, 0.874, 0.621), sideMean: SIMD3(0.861, 0.874, 0.621)),   // endStone
    LodSprite(top: "purpur_block", side: "purpur_block", topLuma: 0.543, sideLuma: 0.543, topMean: SIMD3(0.666, 0.494, 0.665), sideMean: SIMD3(0.666, 0.494, 0.665)),   // purpur
    LodSprite(top: "chorus_plant", side: "chorus_plant", topLuma: 0.265, sideLuma: 0.265, topMean: SIMD3(0.368, 0.224, 0.368), sideMean: SIMD3(0.368, 0.224, 0.368)),   // chorus
    LodSprite(top: "glowstone", side: "glowstone", topLuma: 0.535, sideLuma: 0.535, topMean: SIMD3(0.674, 0.514, 0.331), sideMean: SIMD3(0.674, 0.514, 0.331)),   // glowstone
    LodSprite(top: "sea_lantern", side: "sea_lantern", topLuma: 0.758, sideLuma: 0.758, topMean: SIMD3(0.676, 0.784, 0.745), sideMean: SIMD3(0.676, 0.784, 0.745)),   // seaLantern
    LodSprite(top: "shroomlight", side: "shroomlight", topLuma: 0.632, sideLuma: 0.632, topMean: SIMD3(0.945, 0.575, 0.278), sideMean: SIMD3(0.945, 0.575, 0.278)),   // shroomlight
    LodSprite(top: "pumpkin_top", side: "jack_o_lantern", topLuma: 0.505, sideLuma: 0.621, topMean: SIMD3(0.777, 0.466, 0.096), sideMean: SIMD3(0.841, 0.598, 0.207)),   // jackOLantern
    LodSprite(top: "ochre_froglight_top", side: "ochre_froglight_side", topLuma: 0.955, sideLuma: 0.910, topMean: SIMD3(0.983, 0.961, 0.810), sideMean: SIMD3(0.963, 0.915, 0.713)),   // froglight
    LodSprite(top: "", side: "", topLuma: 1, sideLuma: 1, topMean: SIMD3(1, 1, 1), sideMean: SIMD3(1, 1, 1)),   // light15
    LodSprite(top: "", side: "", topLuma: 1, sideLuma: 1, topMean: SIMD3(1, 1, 1), sideMean: SIMD3(1, 1, 1)),   // light14
    LodSprite(top: "", side: "", topLuma: 1, sideLuma: 1, topMean: SIMD3(1, 1, 1), sideMean: SIMD3(1, 1, 1)),   // light10
    LodSprite(top: "", side: "", topLuma: 1, sideLuma: 1, topMean: SIMD3(1, 1, 1), sideMean: SIMD3(1, 1, 1)),   // light7
    LodSprite(top: "", side: "", topLuma: 1, sideLuma: 1, topMean: SIMD3(1, 1, 1), sideMean: SIMD3(1, 1, 1)),   // (id 62)
    LodSprite(top: "", side: "", topLuma: 1, sideLuma: 1, topMean: SIMD3(1, 1, 1), sideMean: SIMD3(1, 1, 1)),   // (id 63)
    LodSprite(top: "", side: "", topLuma: 1, sideLuma: 1, topMean: SIMD3(1, 1, 1), sideMean: SIMD3(1, 1, 1)),   // (id 64)
    LodSprite(top: "", side: "", topLuma: 1, sideLuma: 1, topMean: SIMD3(1, 1, 1), sideMean: SIMD3(1, 1, 1)),   // (id 65)
    LodSprite(top: "", side: "", topLuma: 1, sideLuma: 1, topMean: SIMD3(1, 1, 1), sideMean: SIMD3(1, 1, 1)),   // (id 66)
    LodSprite(top: "", side: "", topLuma: 1, sideLuma: 1, topMean: SIMD3(1, 1, 1), sideMean: SIMD3(1, 1, 1)),   // (id 67)
    LodSprite(top: "", side: "", topLuma: 1, sideLuma: 1, topMean: SIMD3(1, 1, 1), sideMean: SIMD3(1, 1, 1)),   // (id 68)
    LodSprite(top: "", side: "", topLuma: 1, sideLuma: 1, topMean: SIMD3(1, 1, 1), sideMean: SIMD3(1, 1, 1)),   // (id 69)
    LodSprite(top: "", side: "", topLuma: 1, sideLuma: 1, topMean: SIMD3(1, 1, 1), sideMean: SIMD3(1, 1, 1)),   // (id 70)
    LodSprite(top: "", side: "", topLuma: 1, sideLuma: 1, topMean: SIMD3(1, 1, 1), sideMean: SIMD3(1, 1, 1)),   // (id 71)
    LodSprite(top: "", side: "", topLuma: 1, sideLuma: 1, topMean: SIMD3(1, 1, 1), sideMean: SIMD3(1, 1, 1)),   // (id 72)
    LodSprite(top: "", side: "", topLuma: 1, sideLuma: 1, topMean: SIMD3(1, 1, 1), sideMean: SIMD3(1, 1, 1)),   // (id 73)
    LodSprite(top: "", side: "", topLuma: 1, sideLuma: 1, topMean: SIMD3(1, 1, 1), sideMean: SIMD3(1, 1, 1)),   // (id 74)
    LodSprite(top: "", side: "", topLuma: 1, sideLuma: 1, topMean: SIMD3(1, 1, 1), sideMean: SIMD3(1, 1, 1)),   // (id 75)
    LodSprite(top: "", side: "", topLuma: 1, sideLuma: 1, topMean: SIMD3(1, 1, 1), sideMean: SIMD3(1, 1, 1)),   // (id 76)
    LodSprite(top: "", side: "", topLuma: 1, sideLuma: 1, topMean: SIMD3(1, 1, 1), sideMean: SIMD3(1, 1, 1)),   // (id 77)
    LodSprite(top: "", side: "", topLuma: 1, sideLuma: 1, topMean: SIMD3(1, 1, 1), sideMean: SIMD3(1, 1, 1)),   // (id 78)
    LodSprite(top: "", side: "", topLuma: 1, sideLuma: 1, topMean: SIMD3(1, 1, 1), sideMean: SIMD3(1, 1, 1)),   // (id 79)
    LodSprite(top: "", side: "", topLuma: 1, sideLuma: 1, topMean: SIMD3(1, 1, 1), sideMean: SIMD3(1, 1, 1)),   // (id 80)
    LodSprite(top: "", side: "", topLuma: 1, sideLuma: 1, topMean: SIMD3(1, 1, 1), sideMean: SIMD3(1, 1, 1)),   // (id 81)
    LodSprite(top: "", side: "", topLuma: 1, sideLuma: 1, topMean: SIMD3(1, 1, 1), sideMean: SIMD3(1, 1, 1)),   // (id 82)
    LodSprite(top: "", side: "", topLuma: 1, sideLuma: 1, topMean: SIMD3(1, 1, 1), sideMean: SIMD3(1, 1, 1)),   // (id 83)
    LodSprite(top: "", side: "", topLuma: 1, sideLuma: 1, topMean: SIMD3(1, 1, 1), sideMean: SIMD3(1, 1, 1)),   // (id 84)
    LodSprite(top: "", side: "", topLuma: 1, sideLuma: 1, topMean: SIMD3(1, 1, 1), sideMean: SIMD3(1, 1, 1)),   // (id 85)
    LodSprite(top: "", side: "", topLuma: 1, sideLuma: 1, topMean: SIMD3(1, 1, 1), sideMean: SIMD3(1, 1, 1)),   // (id 86)
    LodSprite(top: "", side: "", topLuma: 1, sideLuma: 1, topMean: SIMD3(1, 1, 1), sideMean: SIMD3(1, 1, 1)),   // (id 87)
    LodSprite(top: "", side: "", topLuma: 1, sideLuma: 1, topMean: SIMD3(1, 1, 1), sideMean: SIMD3(1, 1, 1)),   // (id 88)
    LodSprite(top: "", side: "", topLuma: 1, sideLuma: 1, topMean: SIMD3(1, 1, 1), sideMean: SIMD3(1, 1, 1)),   // (id 89)
    LodSprite(top: "", side: "", topLuma: 1, sideLuma: 1, topMean: SIMD3(1, 1, 1), sideMean: SIMD3(1, 1, 1)),   // (id 90)
    LodSprite(top: "", side: "", topLuma: 1, sideLuma: 1, topMean: SIMD3(1, 1, 1), sideMean: SIMD3(1, 1, 1)),   // (id 91)
    LodSprite(top: "", side: "", topLuma: 1, sideLuma: 1, topMean: SIMD3(1, 1, 1), sideMean: SIMD3(1, 1, 1)),   // (id 92)
    LodSprite(top: "", side: "", topLuma: 1, sideLuma: 1, topMean: SIMD3(1, 1, 1), sideMean: SIMD3(1, 1, 1)),   // (id 93)
    LodSprite(top: "", side: "", topLuma: 1, sideLuma: 1, topMean: SIMD3(1, 1, 1), sideMean: SIMD3(1, 1, 1)),   // (id 94)
    LodSprite(top: "", side: "", topLuma: 1, sideLuma: 1, topMean: SIMD3(1, 1, 1), sideMean: SIMD3(1, 1, 1)),   // (id 95)
    LodSprite(top: "", side: "", topLuma: 1, sideLuma: 1, topMean: SIMD3(1, 1, 1), sideMean: SIMD3(1, 1, 1)),   // (id 96)
    LodSprite(top: "", side: "", topLuma: 1, sideLuma: 1, topMean: SIMD3(1, 1, 1), sideMean: SIMD3(1, 1, 1)),   // (id 97)
    LodSprite(top: "", side: "", topLuma: 1, sideLuma: 1, topMean: SIMD3(1, 1, 1), sideMean: SIMD3(1, 1, 1)),   // (id 98)
    LodSprite(top: "", side: "", topLuma: 1, sideLuma: 1, topMean: SIMD3(1, 1, 1), sideMean: SIMD3(1, 1, 1)),   // (id 99)
    LodSprite(top: "", side: "", topLuma: 1, sideLuma: 1, topMean: SIMD3(1, 1, 1), sideMean: SIMD3(1, 1, 1)),   // (id 100)
    LodSprite(top: "", side: "", topLuma: 1, sideLuma: 1, topMean: SIMD3(1, 1, 1), sideMean: SIMD3(1, 1, 1)),   // (id 101)
    LodSprite(top: "", side: "", topLuma: 1, sideLuma: 1, topMean: SIMD3(1, 1, 1), sideMean: SIMD3(1, 1, 1)),   // (id 102)
    LodSprite(top: "", side: "", topLuma: 1, sideLuma: 1, topMean: SIMD3(1, 1, 1), sideMean: SIMD3(1, 1, 1)),   // (id 103)
    LodSprite(top: "", side: "", topLuma: 1, sideLuma: 1, topMean: SIMD3(1, 1, 1), sideMean: SIMD3(1, 1, 1)),   // (id 104)
    LodSprite(top: "", side: "", topLuma: 1, sideLuma: 1, topMean: SIMD3(1, 1, 1), sideMean: SIMD3(1, 1, 1)),   // (id 105)
    LodSprite(top: "", side: "", topLuma: 1, sideLuma: 1, topMean: SIMD3(1, 1, 1), sideMean: SIMD3(1, 1, 1)),   // (id 106)
    LodSprite(top: "", side: "", topLuma: 1, sideLuma: 1, topMean: SIMD3(1, 1, 1), sideMean: SIMD3(1, 1, 1)),   // (id 107)
    LodSprite(top: "", side: "", topLuma: 1, sideLuma: 1, topMean: SIMD3(1, 1, 1), sideMean: SIMD3(1, 1, 1)),   // (id 108)
    LodSprite(top: "", side: "", topLuma: 1, sideLuma: 1, topMean: SIMD3(1, 1, 1), sideMean: SIMD3(1, 1, 1)),   // (id 109)
    LodSprite(top: "", side: "", topLuma: 1, sideLuma: 1, topMean: SIMD3(1, 1, 1), sideMean: SIMD3(1, 1, 1)),   // (id 110)
    LodSprite(top: "", side: "", topLuma: 1, sideLuma: 1, topMean: SIMD3(1, 1, 1), sideMean: SIMD3(1, 1, 1)),   // (id 111)
    LodSprite(top: "", side: "", topLuma: 1, sideLuma: 1, topMean: SIMD3(1, 1, 1), sideMean: SIMD3(1, 1, 1)),   // (id 112)
    LodSprite(top: "", side: "", topLuma: 1, sideLuma: 1, topMean: SIMD3(1, 1, 1), sideMean: SIMD3(1, 1, 1)),   // (id 113)
    LodSprite(top: "", side: "", topLuma: 1, sideLuma: 1, topMean: SIMD3(1, 1, 1), sideMean: SIMD3(1, 1, 1)),   // (id 114)
    LodSprite(top: "", side: "", topLuma: 1, sideLuma: 1, topMean: SIMD3(1, 1, 1), sideMean: SIMD3(1, 1, 1)),   // (id 115)
    LodSprite(top: "", side: "", topLuma: 1, sideLuma: 1, topMean: SIMD3(1, 1, 1), sideMean: SIMD3(1, 1, 1)),   // (id 116)
    LodSprite(top: "", side: "", topLuma: 1, sideLuma: 1, topMean: SIMD3(1, 1, 1), sideMean: SIMD3(1, 1, 1)),   // (id 117)
    LodSprite(top: "", side: "", topLuma: 1, sideLuma: 1, topMean: SIMD3(1, 1, 1), sideMean: SIMD3(1, 1, 1)),   // (id 118)
    LodSprite(top: "", side: "", topLuma: 1, sideLuma: 1, topMean: SIMD3(1, 1, 1), sideMean: SIMD3(1, 1, 1)),   // (id 119)
    LodSprite(top: "", side: "", topLuma: 1, sideLuma: 1, topMean: SIMD3(1, 1, 1), sideMean: SIMD3(1, 1, 1)),   // (id 120)
    LodSprite(top: "", side: "", topLuma: 1, sideLuma: 1, topMean: SIMD3(1, 1, 1), sideMean: SIMD3(1, 1, 1)),   // (id 121)
    LodSprite(top: "", side: "", topLuma: 1, sideLuma: 1, topMean: SIMD3(1, 1, 1), sideMean: SIMD3(1, 1, 1)),   // (id 122)
    LodSprite(top: "", side: "", topLuma: 1, sideLuma: 1, topMean: SIMD3(1, 1, 1), sideMean: SIMD3(1, 1, 1)),   // (id 123)
    LodSprite(top: "", side: "", topLuma: 1, sideLuma: 1, topMean: SIMD3(1, 1, 1), sideMean: SIMD3(1, 1, 1)),   // (id 124)
    LodSprite(top: "", side: "", topLuma: 1, sideLuma: 1, topMean: SIMD3(1, 1, 1), sideMean: SIMD3(1, 1, 1)),   // (id 125)
    LodSprite(top: "", side: "", topLuma: 1, sideLuma: 1, topMean: SIMD3(1, 1, 1), sideMean: SIMD3(1, 1, 1)),   // (id 126)
    LodSprite(top: "", side: "", topLuma: 1, sideLuma: 1, topMean: SIMD3(1, 1, 1), sideMean: SIMD3(1, 1, 1)),   // (id 127)
    LodSprite(top: "", side: "", topLuma: 1, sideLuma: 1, topMean: SIMD3(1, 1, 1), sideMean: SIMD3(1, 1, 1)),   // (id 128)
    LodSprite(top: "", side: "", topLuma: 1, sideLuma: 1, topMean: SIMD3(1, 1, 1), sideMean: SIMD3(1, 1, 1)),   // (id 129)
    LodSprite(top: "", side: "", topLuma: 1, sideLuma: 1, topMean: SIMD3(1, 1, 1), sideMean: SIMD3(1, 1, 1)),   // (id 130)
    LodSprite(top: "", side: "", topLuma: 1, sideLuma: 1, topMean: SIMD3(1, 1, 1), sideMean: SIMD3(1, 1, 1)),   // (id 131)
    LodSprite(top: "", side: "", topLuma: 1, sideLuma: 1, topMean: SIMD3(1, 1, 1), sideMean: SIMD3(1, 1, 1)),   // (id 132)
    LodSprite(top: "", side: "", topLuma: 1, sideLuma: 1, topMean: SIMD3(1, 1, 1), sideMean: SIMD3(1, 1, 1)),   // (id 133)
    LodSprite(top: "", side: "", topLuma: 1, sideLuma: 1, topMean: SIMD3(1, 1, 1), sideMean: SIMD3(1, 1, 1)),   // (id 134)
    LodSprite(top: "", side: "", topLuma: 1, sideLuma: 1, topMean: SIMD3(1, 1, 1), sideMean: SIMD3(1, 1, 1)),   // (id 135)
    LodSprite(top: "", side: "", topLuma: 1, sideLuma: 1, topMean: SIMD3(1, 1, 1), sideMean: SIMD3(1, 1, 1)),   // (id 136)
    LodSprite(top: "", side: "", topLuma: 1, sideLuma: 1, topMean: SIMD3(1, 1, 1), sideMean: SIMD3(1, 1, 1)),   // (id 137)
    LodSprite(top: "", side: "", topLuma: 1, sideLuma: 1, topMean: SIMD3(1, 1, 1), sideMean: SIMD3(1, 1, 1)),   // (id 138)
    LodSprite(top: "", side: "", topLuma: 1, sideLuma: 1, topMean: SIMD3(1, 1, 1), sideMean: SIMD3(1, 1, 1)),   // (id 139)
    LodSprite(top: "", side: "", topLuma: 1, sideLuma: 1, topMean: SIMD3(1, 1, 1), sideMean: SIMD3(1, 1, 1)),   // (id 140)
    LodSprite(top: "", side: "", topLuma: 1, sideLuma: 1, topMean: SIMD3(1, 1, 1), sideMean: SIMD3(1, 1, 1)),   // (id 141)
    LodSprite(top: "", side: "", topLuma: 1, sideLuma: 1, topMean: SIMD3(1, 1, 1), sideMean: SIMD3(1, 1, 1)),   // (id 142)
    LodSprite(top: "", side: "", topLuma: 1, sideLuma: 1, topMean: SIMD3(1, 1, 1), sideMean: SIMD3(1, 1, 1)),   // (id 143)
    LodSprite(top: "", side: "", topLuma: 1, sideLuma: 1, topMean: SIMD3(1, 1, 1), sideMean: SIMD3(1, 1, 1)),   // (id 144)
    LodSprite(top: "", side: "", topLuma: 1, sideLuma: 1, topMean: SIMD3(1, 1, 1), sideMean: SIMD3(1, 1, 1)),   // (id 145)
    LodSprite(top: "", side: "", topLuma: 1, sideLuma: 1, topMean: SIMD3(1, 1, 1), sideMean: SIMD3(1, 1, 1)),   // (id 146)
    LodSprite(top: "", side: "", topLuma: 1, sideLuma: 1, topMean: SIMD3(1, 1, 1), sideMean: SIMD3(1, 1, 1)),   // (id 147)
    LodSprite(top: "", side: "", topLuma: 1, sideLuma: 1, topMean: SIMD3(1, 1, 1), sideMean: SIMD3(1, 1, 1)),   // (id 148)
    LodSprite(top: "", side: "", topLuma: 1, sideLuma: 1, topMean: SIMD3(1, 1, 1), sideMean: SIMD3(1, 1, 1)),   // (id 149)
    LodSprite(top: "", side: "", topLuma: 1, sideLuma: 1, topMean: SIMD3(1, 1, 1), sideMean: SIMD3(1, 1, 1)),   // (id 150)
    LodSprite(top: "", side: "", topLuma: 1, sideLuma: 1, topMean: SIMD3(1, 1, 1), sideMean: SIMD3(1, 1, 1)),   // (id 151)
    LodSprite(top: "", side: "", topLuma: 1, sideLuma: 1, topMean: SIMD3(1, 1, 1), sideMean: SIMD3(1, 1, 1)),   // (id 152)
    LodSprite(top: "", side: "", topLuma: 1, sideLuma: 1, topMean: SIMD3(1, 1, 1), sideMean: SIMD3(1, 1, 1)),   // (id 153)
    LodSprite(top: "", side: "", topLuma: 1, sideLuma: 1, topMean: SIMD3(1, 1, 1), sideMean: SIMD3(1, 1, 1)),   // (id 154)
    LodSprite(top: "", side: "", topLuma: 1, sideLuma: 1, topMean: SIMD3(1, 1, 1), sideMean: SIMD3(1, 1, 1)),   // (id 155)
    LodSprite(top: "", side: "", topLuma: 1, sideLuma: 1, topMean: SIMD3(1, 1, 1), sideMean: SIMD3(1, 1, 1)),   // (id 156)
    LodSprite(top: "", side: "", topLuma: 1, sideLuma: 1, topMean: SIMD3(1, 1, 1), sideMean: SIMD3(1, 1, 1)),   // (id 157)
    LodSprite(top: "", side: "", topLuma: 1, sideLuma: 1, topMean: SIMD3(1, 1, 1), sideMean: SIMD3(1, 1, 1)),   // (id 158)
    LodSprite(top: "", side: "", topLuma: 1, sideLuma: 1, topMean: SIMD3(1, 1, 1), sideMean: SIMD3(1, 1, 1)),   // (id 159)
    LodSprite(top: "yellow_poplar_leaves", side: "yellow_poplar_leaves", topLuma: 0.565, sideLuma: 0.565, topMean: SIMD3(0.842, 0.524, 0.158), sideMean: SIMD3(0.842, 0.524, 0.158)),   // yellowPoplarLeaves
    LodSprite(top: "red_poplar_leaves", side: "red_poplar_leaves", topLuma: 0.264, sideLuma: 0.264, topMean: SIMD3(0.604, 0.174, 0.154), sideMean: SIMD3(0.604, 0.174, 0.154)),   // redPoplarLeaves
    LodSprite(top: "orange_poplar_leaves", side: "orange_poplar_leaves", topLuma: 0.406, sideLuma: 0.406, topMean: SIMD3(0.739, 0.339, 0.094), sideMean: SIMD3(0.739, 0.339, 0.094)),   // orangePoplarLeaves
    LodSprite(top: "red_mushroom_block", side: "red_mushroom_block", topLuma: 0.311, sideLuma: 0.311, topMean: SIMD3(0.785, 0.184, 0.177), sideMean: SIMD3(0.785, 0.184, 0.177)),   // redMushroomBlock
    LodSprite(top: "brown_mushroom_block", side: "brown_mushroom_block", topLuma: 0.461, sideLuma: 0.461, topMean: SIMD3(0.586, 0.438, 0.319), sideMean: SIMD3(0.586, 0.438, 0.319)),   // brownMushroomBlock
    LodSprite(top: "mushroom_stem", side: "mushroom_stem", topLuma: 0.773, sideLuma: 0.773, topMean: SIMD3(0.797, 0.771, 0.728), sideMean: SIMD3(0.797, 0.771, 0.728)),   // mushroomStem
    LodSprite(top: "prismarine", side: "prismarine", topLuma: 0.564, sideLuma: 0.564, topMean: SIMD3(0.390, 0.613, 0.592), sideMean: SIMD3(0.390, 0.613, 0.592)),   // prismarine
    LodSprite(top: "dark_prismarine", side: "dark_prismarine", topLuma: 0.322, sideLuma: 0.322, topMean: SIMD3(0.203, 0.359, 0.298), sideMean: SIMD3(0.203, 0.359, 0.298)),   // darkPrismarine
    LodSprite(top: "magma", side: "magma", topLuma: 0.306, sideLuma: 0.306, topMean: SIMD3(0.560, 0.249, 0.124), sideMean: SIMD3(0.560, 0.249, 0.124)),   // magma
    LodSprite(top: "grass_block_side_overlay", side: "grass_block_side", topLuma: 0.606, sideLuma: 0.425, topMean: SIMD3(0.606, 0.606, 0.606), sideMean: SIMD3(0.497, 0.420, 0.257)),   // grass side (not a material)
]
