import simd

// Generated by lod_colors.py from Minecraft 26.3's block textures: the mean color of each material's
// representative texture's opaque texels, with the plains grass/foliage/water tints. Indexed by
// MetalMCCore.Mat raw value. Keeps far LOD terrain close to the average color of vanilla's textured
// terrain at the seam.
let lodMaterialColors: [SIMD4<Float>] = [
    SIMD4(0, 0, 0, 0),   // air
    SIMD4(0.492, 0.492, 0.492, 1),   // stone
    SIMD4(0.526, 0.378, 0.263, 1),   // dirt
    SIMD4(0.329, 0.429, 0.202, 1),   // grass
    SIMD4(0.859, 0.813, 0.640, 1),   // sand
    SIMD4(0.172, 0.321, 0.621, 1),   // water
    SIMD4(0.492, 0.492, 0.492, 1),   // unknown
    SIMD4(0.314, 0.314, 0.324, 1),   // deepslate
    SIMD4(0.517, 0.500, 0.496, 1),   // gravel
    SIMD4(0.428, 0.334, 0.199, 1),   // log
    SIMD4(0.636, 0.513, 0.308, 1),   // planks
    SIMD4(0.264, 0.379, 0.104, 1),   // leaves
    SIMD4(0.900, 0.678, 0.761, 1),   // cherryLeaves
    SIMD4(0.977, 0.997, 0.997, 1),   // snow
    SIMD4(0.571, 0.721, 0.996, 1),   // ice
    SIMD4(0.630, 0.653, 0.704, 1),   // clay
    SIMD4(0.597, 0.369, 0.266, 1),   // terracotta
    SIMD4(0.833, 0.353, 0.071, 1),   // lava
    SIMD4(0.501, 0.499, 0.500, 1),   // cobblestone
    SIMD4(0.592, 0.383, 0.326, 1),   // bricks
    SIMD4(0.582, 0.477, 0.256, 1),   // path
    SIMD4(0.561, 0.402, 0.278, 1),   // farmland
    SIMD4(0.651, 0.546, 0.049, 1),   // hay
    SIMD4(0.916, 0.927, 0.929, 1),   // wool
    SIMD4(0.349, 0.430, 0.178, 1),   // moss
    SIMD4(0.215, 0.129, 0.174, 1),   // cherryWood
    SIMD4(0.717, 0.718, 0.714, 1),   // lightStone
    SIMD4(0.586, 0.405, 0.337, 1),   // granite
    SIMD4(0.878, 0.840, 0.668, 1),   // sandstone
    SIMD4(0.236, 0.225, 0.238, 1),   // mud
    SIMD4(0.525, 0.384, 0.750, 1),   // amethyst
    SIMD4(0.767, 0.450, 0.095, 1),   // pumpkin
]

/// Block textures used for LOD texture detail (names under block/ in the block atlas), with the mean luma
/// of each texture's opaque texels. The LOD multiplies its flat color by texel luma / mean luma.
struct LodSprite {
    let top: String
    let side: String
    let topLuma: Float
    let sideLuma: Float
}

let lodMaterialSprites: [LodSprite] = [
    LodSprite(top: "", side: "", topLuma: 1, sideLuma: 1),   // air
    LodSprite(top: "stone", side: "stone", topLuma: 0.492, sideLuma: 0.492),   // stone
    LodSprite(top: "dirt", side: "dirt", topLuma: 0.401, sideLuma: 0.401),   // dirt
    LodSprite(top: "grass_block_top", side: "dirt", topLuma: 0.578, sideLuma: 0.401),   // grass
    LodSprite(top: "sand", side: "sand", topLuma: 0.810, sideLuma: 0.810),   // sand
    LodSprite(top: "water_still", side: "water_still", topLuma: 0.694, sideLuma: 0.694),   // water
    LodSprite(top: "stone", side: "stone", topLuma: 0.492, sideLuma: 0.492),   // unknown
    LodSprite(top: "deepslate_top", side: "deepslate", topLuma: 0.343, sideLuma: 0.315),   // deepslate
    LodSprite(top: "gravel", side: "gravel", topLuma: 0.503, sideLuma: 0.503),   // gravel
    LodSprite(top: "oak_log_top", side: "oak_log", topLuma: 0.488, sideLuma: 0.344),   // log
    LodSprite(top: "oak_planks", side: "oak_planks", topLuma: 0.524, sideLuma: 0.524),   // planks
    LodSprite(top: "oak_leaves", side: "oak_leaves", topLuma: 0.565, sideLuma: 0.565),   // leaves
    LodSprite(top: "cherry_leaves", side: "cherry_leaves", topLuma: 0.731, sideLuma: 0.731),   // cherryLeaves
    LodSprite(top: "snow", side: "snow", topLuma: 0.993, sideLuma: 0.993),   // snow
    LodSprite(top: "ice", side: "ice", topLuma: 0.709, sideLuma: 0.709),   // ice
    LodSprite(top: "clay", side: "clay", topLuma: 0.652, sideLuma: 0.652),   // clay
    LodSprite(top: "terracotta", side: "terracotta", topLuma: 0.410, sideLuma: 0.410),   // terracotta
    LodSprite(top: "lava_still", side: "lava_still", topLuma: 0.435, sideLuma: 0.435),   // lava
    LodSprite(top: "cobblestone", side: "cobblestone", topLuma: 0.500, sideLuma: 0.500),   // cobblestone
    LodSprite(top: "bricks", side: "bricks", topLuma: 0.423, sideLuma: 0.423),   // bricks
    LodSprite(top: "dirt_path_top", side: "dirt_path_side", topLuma: 0.483, sideLuma: 0.416),   // path
    LodSprite(top: "farmland", side: "dirt", topLuma: 0.427, sideLuma: 0.401),   // farmland
    LodSprite(top: "hay_block_top", side: "hay_block_side", topLuma: 0.532, sideLuma: 0.533),   // hay
    LodSprite(top: "white_wool", side: "white_wool", topLuma: 0.925, sideLuma: 0.925),   // wool
    LodSprite(top: "moss_block", side: "moss_block", topLuma: 0.395, sideLuma: 0.395),   // moss
    LodSprite(top: "cherry_log_top", side: "cherry_log", topLuma: 0.589, sideLuma: 0.151),   // cherryWood
    LodSprite(top: "calcite", side: "calcite", topLuma: 0.878, sideLuma: 0.878),   // lightStone
    LodSprite(top: "granite", side: "granite", topLuma: 0.438, sideLuma: 0.438),   // granite
    LodSprite(top: "sandstone_top", side: "sandstone", topLuma: 0.836, sideLuma: 0.795),   // sandstone
    LodSprite(top: "mud", side: "mud", topLuma: 0.229, sideLuma: 0.229),   // mud
    LodSprite(top: "amethyst_block", side: "amethyst_block", topLuma: 0.441, sideLuma: 0.441),   // amethyst
    LodSprite(top: "pumpkin_top", side: "pumpkin_side", topLuma: 0.505, sideLuma: 0.492),   // pumpkin
]
