"""Averages Minecraft block textures into LOD material colors and writes LodColors.swift.
Pure Python (no PIL): minimal PNG decoder for 8-bit RGB/RGBA/gray and 1/2/4/8-bit palette images."""
import glob
import os
import struct
import zipfile
import zlib

jar = glob.glob(os.path.expanduser("~/.gradle/caches/fabric-loom/minecraftMaven/net/minecraft/minecraft-clientonly-deobf/26.3/*.jar"))[0]
z = zipfile.ZipFile(jar)

def png(name):
    data = z.read(f"assets/minecraft/textures/block/{name}.png")
    assert data[:8] == b"\x89PNG\r\n\x1a\n"
    pos, idat, plte, trns = 8, b"", None, None
    while pos < len(data):
        n, typ = struct.unpack(">I4s", data[pos:pos + 8])
        body = data[pos + 8:pos + 8 + n]
        if typ == b"IHDR":
            w, h, depth, ctype, _, _, interlace = struct.unpack(">IIBBBBB", body)
        elif typ == b"PLTE":
            plte = body
        elif typ == b"tRNS":
            trns = body
        elif typ == b"IDAT":
            idat += body
        pos += 12 + n
    assert interlace == 0, name
    raw = zlib.decompress(idat)
    chans = {0: 1, 2: 3, 3: 1, 4: 2, 6: 4}[ctype]
    bpp_bits = chans * depth
    stride = (w * bpp_bits + 7) // 8
    bpp = max(1, bpp_bits // 8)
    rows, prev, i = [], bytearray(stride), 0
    for _ in range(h):
        f = raw[i]; line = bytearray(raw[i + 1:i + 1 + stride]); i += 1 + stride
        for x in range(stride):
            a = line[x - bpp] if x >= bpp else 0
            b = prev[x]
            c = prev[x - bpp] if x >= bpp else 0
            if f == 1: line[x] = (line[x] + a) & 255
            elif f == 2: line[x] = (line[x] + b) & 255
            elif f == 3: line[x] = (line[x] + (a + b) // 2) & 255
            elif f == 4:
                p = a + b - c; pa, pb, pc = abs(p - a), abs(p - b), abs(p - c)
                line[x] = (line[x] + (a if pa <= pb and pa <= pc else (b if pb <= pc else c))) & 255
        rows.append(line); prev = line
    px = []
    for line in rows:
        for x in range(w):
            if ctype == 3:
                bit = x * depth
                v = (line[bit // 8] >> (8 - depth - bit % 8)) & ((1 << depth) - 1)
                r, g, b = plte[3 * v:3 * v + 3]
                a = trns[v] if trns and v < len(trns) else 255
            elif ctype == 6: r, g, b, a = line[4 * x:4 * x + 4]
            elif ctype == 2: (r, g, b), a = line[3 * x:3 * x + 3], 255
            elif ctype == 4: r = g = b = line[2 * x]; a = line[2 * x + 1]
            else: r = g = b = line[x]; a = 255
            px.append((r, g, b, a))
    return w, h, px

def average(name, tint=None):
    w, h, px = png(name)
    opaque = [p for p in px if p[3] >= 128]
    n = len(opaque)
    r, g, b = (sum(p[k] for p in opaque) / n / 255 for k in range(3))
    if tint is not None:
        r, g, b = r * ((tint >> 16) & 255) / 255, g * ((tint >> 8) & 255) / 255, b * (tint & 255) / 255
    return (r, g, b)

def mix(*cs):
    return tuple(sum(c[k] for c in cs) / len(cs) for k in range(3))

GRASS, FOLIAGE, WATER = 0x91BD59, 0x77AB2F, 0x3F76E4   # plains defaults
colors = [
    ("air", None), ("stone", average("stone")), ("dirt", average("dirt")),
    ("grass", average("grass_block_top", GRASS)), ("sand", average("sand")),
    ("water", average("water_still", WATER)), ("unknown", average("stone")),
    ("deepslate", average("deepslate")), ("gravel", average("gravel")), ("log", average("oak_log")),
    ("planks", average("oak_planks")), ("leaves", average("oak_leaves", FOLIAGE)),
    ("cherryLeaves", average("cherry_leaves")), ("snow", average("snow")), ("ice", average("ice")),
    ("clay", average("clay")), ("terracotta", average("terracotta")), ("lava", average("lava_still")),
    ("cobblestone", average("cobblestone")), ("bricks", average("bricks")), ("path", average("dirt_path_top")),
    ("farmland", average("farmland")), ("hay", average("hay_block_top")), ("wool", average("white_wool")),
    ("moss", average("moss_block")), ("cherryWood", average("cherry_log")),
    ("lightStone", mix(average("diorite"), average("andesite"), average("calcite"))),
    ("granite", average("granite")), ("sandstone", average("sandstone_top")), ("mud", average("mud")),
    ("amethyst", average("amethyst_block")), ("pumpkin", average("pumpkin_side")),
]
lines = []
for name, c in colors:
    if c is None:
        lines.append(f"    SIMD4(0, 0, 0, 0),   // {name}")
    else:
        lines.append(f"    SIMD4({c[0]:.3f}, {c[1]:.3f}, {c[2]:.3f}, 1),   // {name}")
out = """import simd

// Generated by lod_colors.py from Minecraft 26.3's block textures: the mean color of each material's
// representative texture's opaque texels, with the plains grass/foliage/water tints. Indexed by
// MetalMCCore.Mat raw value. Keeps far LOD terrain close to the average color of vanilla's textured
// terrain at the seam.
let lodMaterialColors: [SIMD4<Float>] = [
""" + "\n".join(lines) + "\n]\n"
open(os.path.expanduser("~/Projects/metal-mc/Sources/MetalMCNative/LodColors.swift"), "w").write(out)
print(out)
